version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels: [dependencies]
  - package-ecosystem: npm
    directory: /Website
    schedule:
      interval: monthly
    labels: [dependencies, website]
    groups:
      website-dependencies:
        patterns: ['*']
